In [1]:
import pandas as pd

# Read Data

In [2]:
df1=pd.read_csv(r"Hospital_Inpatient_Discharges__SPARCS_De-Identified___2022.csv")
df2=pd.read_csv(r"Hospital_Inpatient_Discharges__SPARCS_De-Identified___2023.csv")

C:\Users\Hamza\AppData\Local\Temp\ipykernel_15948\248204720.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv(r"Hospital_Inpatient_Discharges__SPARCS_De-Identified___2022.csv")
C:\Users\Hamza\AppData\Local\Temp\ipykernel_15948\248204720.py:2: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv(r"Hospital_Inpatient_Discharges__SPARCS_De-Identified___2023.csv")

In [3]:
df1.head(15)

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Manhattan,7002021.0,1454.0,Metropolitan Hospital Center,18 to 29,100,M,Other Race,Spanish/Hispanic,...,Moderate,Major,Medical,Self-Pay,NaN,NaN,NaN,Y,"21,943.33","19,793.21"
1,New York City,Queens,7003000.0,1626.0,Elmhurst Hospital Center,50 to 69,113,M,White,Unknown,...,Minor,Minor,Medical,Medicare,NaN,NaN,NaN,Y,"39,527.97","18,372.44"
2,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,M,Other Race,Unknown,...,Major,Major,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,"102,926.99","25,977.53"
3,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,50 to 69,109,M,White,Not Span/Hispanic,...,Major,Major,Medical,Medicare,NaN,NaN,NaN,Y,"85,344.09","18,830.76"
4,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,F,White,Not Span/Hispanic,...,Extreme,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"218,623.85","42,449.25"
5,New York City,Bronx,7000006.0,3058.0,Montefiore Med Center - Jack D Weiler Hosp of ...,50 to 69,107,F,White,Not Span/Hispanic,...,Major,Major,Medical,Medicaid,NaN,NaN,NaN,Y,"51,514.62","7,552.54"
6,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,50 to 69,NaN,M,Other Race,Unknown,...,Moderate,Moderate,Medical,Private Health Insurance,NaN,NaN,NaN,Y,"13,831.84","2,549.13"
7,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,70 or Older,104,M,Black/African American,Not Span/Hispanic,...,Moderate,Moderate,Medical,Medicare,Medicaid,NaN,NaN,Y,"85,119.39","15,859.37"
8,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,30 to 49,109,F,Other Race,Not Span/Hispanic,...,Minor,Minor,Medical,Blue Cross/Blue Shield,NaN,NaN,NaN,N,"35,569.32","11,200.23"
9,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,70 or Older,100,F,Black/African American,Unknown,...,Moderate,Major,Medical,Medicare,NaN,NaN,NaN,Y,"51,928.64","39,840.80"
10,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,50 to 69,104,F,Black/African American,Unknown,...,Major,Major,Medical,Medicaid,NaN,NaN,NaN,Y,"27,942.07","21,437.77"
11,New York City,Manhattan,7002009.0,1445.0,Harlem Hospital Center,70 or Older,100,M,Black/African American,Unknown,...,Minor,Moderate,Medical,Medicare,NaN,NaN,NaN,Y,"42,037.19","32,251.86"
12,New York City,Bronx,7000002.0,1165.0,Jacobi Medical Center,30 to 49,104,M,Other Race,Spanish/Hispanic,...,Major,Moderate,Medical,Medicaid,NaN,NaN,NaN,Y,"10,369.96","6,154.97"
13,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,0 to 17,104,M,Other Race,Spanish/Hispanic,...,Major,Major,Medical,Medicaid,NaN,NaN,NaN,Y,"143,291.04","30,096.26"
14,New York City,Queens,7003000.0,1626.0,Elmhurst Hospital Center,50 to 69,113,F,Other Race,Unknown,...,Major,Major,Medical,Medicaid,NaN,NaN,NaN,Y,"34,480.35","16,026.33"

In [4]:
df1.columns

Index(['Hospital Service Area', 'Hospital County',
       'Operating Certificate Number', 'Permanent Facility Id',
       'Facility Name', 'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race',
       'Ethnicity', 'Length of Stay', 'Type of Admission',
       'Patient Disposition', 'Discharge Year', 'CCSR Diagnosis Code',
       'CCSR Diagnosis Description', 'CCSR Procedure Code',
       'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description',
       'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code',
       'APR Severity of Illness Description', 'APR Risk of Mortality',
       'APR Medical Surgical Description', 'Payment Typology 1',
       'Payment Typology 2', 'Payment Typology 3', 'Birth Weight',
       'Emergency Department Indicator', 'Total Charges', 'Total Costs'],
      dtype='object')

# Merge Data

In [5]:
df = pd.concat([df1, df2], ignore_index=True)

In [6]:
df1.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2103433 entries, 0 to 2103432
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 3.2 GB

In [7]:
df2.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2125754 entries, 0 to 2125753
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 3.3 GB

In [8]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4229187 entries, 0 to 4229186
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 6.5 GB

In [9]:
sum(df1.duplicated())

2923

In [10]:
sum(df2.duplicated())

2648

In [11]:
(df1.isna().mean() * 100).round(2)

Hospital Service Area                   0.26
Hospital County                         0.26
Operating Certificate Number            0.28
Permanent Facility Id                   0.26
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     1.96
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.00
CCSR Diagnosis Description              0.00
CCSR Procedure Code                    27.71
CCSR Procedure Description             27.71
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.03
APR Risk of Mortality                   0.03
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     53.32
Payment Typology 3                     86.26
Birth Weight                           90.08
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

In [12]:
(df.isna().mean() * 100).round(2)

Hospital Service Area                   0.25
Hospital County                         0.25
Operating Certificate Number            0.27
Permanent Facility Id                   0.25
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     1.97
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.00
CCSR Diagnosis Description              0.00
CCSR Procedure Code                    28.23
CCSR Procedure Description             28.23
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.03
APR Risk of Mortality                   0.03
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     52.86
Payment Typology 3                     86.48
Birth Weight                           90.24
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

In [13]:
df1.isna().sum()

Hospital Service Area                     5390
Hospital County                           5390
Operating Certificate Number              5961
Permanent Facility Id                     5390
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      41227
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                          0
CCSR Diagnosis Description                   0
CCSR Procedure Code                     582815
CCSR Procedure Description              582815
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        636
APR Risk of Mortality                      636
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                     1121497
Payment Typology 3                     1814362
Birth Weight                           1894796
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [14]:
df2.isna().sum()

Hospital Service Area                     5333
Hospital County                           5333
Operating Certificate Number              5333
Permanent Facility Id                     5333
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      41883
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                          0
CCSR Diagnosis Description                   0
CCSR Procedure Code                     611024
CCSR Procedure Description              611024
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        474
APR Risk of Mortality                      474
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                     1114046
Payment Typology 3                     1843136
Birth Weight                           1921751
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [15]:
df.isna().sum()

Hospital Service Area                    10723
Hospital County                          10723
Operating Certificate Number             11294
Permanent Facility Id                    10723
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      83110
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                          0
CCSR Diagnosis Description                   0
CCSR Procedure Code                    1193839
CCSR Procedure Description             1193839
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description       1110
APR Risk of Mortality                     1110
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                     2235543
Payment Typology 3                     3657498
Birth Weight                           3816547
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [16]:
(df1.isna().mean() * 100).round(2)

Hospital Service Area                   0.26
Hospital County                         0.26
Operating Certificate Number            0.28
Permanent Facility Id                   0.26
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     1.96
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.00
CCSR Diagnosis Description              0.00
CCSR Procedure Code                    27.71
CCSR Procedure Description             27.71
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.03
APR Risk of Mortality                   0.03
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     53.32
Payment Typology 3                     86.26
Birth Weight                           90.08
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

In [17]:
(df2.isna().mean() * 100).round(2)

Hospital Service Area                   0.25
Hospital County                         0.25
Operating Certificate Number            0.25
Permanent Facility Id                   0.25
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     1.97
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.00
CCSR Diagnosis Description              0.00
CCSR Procedure Code                    28.74
CCSR Procedure Description             28.74
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.02
APR Risk of Mortality                   0.02
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     52.41
Payment Typology 3                     86.71
Birth Weight                           90.40
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

In [18]:
(df.isna().mean() * 100).round(2)

Hospital Service Area                   0.25
Hospital County                         0.25
Operating Certificate Number            0.27
Permanent Facility Id                   0.25
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     1.97
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.00
CCSR Diagnosis Description              0.00
CCSR Procedure Code                    28.23
CCSR Procedure Description             28.23
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.03
APR Risk of Mortality                   0.03
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     52.86
Payment Typology 3                     86.48
Birth Weight                           90.24
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

In [19]:
df

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Manhattan,7002021.0,1454.0,Metropolitan Hospital Center,18 to 29,100,M,Other Race,Spanish/Hispanic,...,Moderate,Major,Medical,Self-Pay,NaN,NaN,NaN,Y,"21,943.33","19,793.21"
1,New York City,Queens,7003000.0,1626.0,Elmhurst Hospital Center,50 to 69,113,M,White,Unknown,...,Minor,Minor,Medical,Medicare,NaN,NaN,NaN,Y,"39,527.97","18,372.44"
2,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,M,Other Race,Unknown,...,Major,Major,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,"102,926.99","25,977.53"
3,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,50 to 69,109,M,White,Not Span/Hispanic,...,Major,Major,Medical,Medicare,NaN,NaN,NaN,Y,"85,344.09","18,830.76"
4,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,F,White,Not Span/Hispanic,...,Extreme,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"218,623.85","42,449.25"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4229182,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,115,M,Other Race,Not Span/Hispanic,...,Minor,Minor,Medical,Private Health Insurance,Self-Pay,NaN,NaN,Y,"27,074.71","4,718.63"
4229183,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,114,F,Other Race,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,Self-Pay,NaN,01900,N,"216,053.15","27,000.66"
4229184,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,109,F,White,Not Span/Hispanic,...,Minor,Minor,Medical,Medicaid,Medicaid,Self-Pay,NaN,Y,"24,867.76","4,291.06"
4229185,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,117,M,White,Spanish/Hispanic,...,Minor,Minor,Medical,Blue Cross/Blue Shield,Blue Cross/Blue Shield,Self-Pay,NaN,N,"46,873.00","6,210.75"
4229186,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,103,F,White,Not Span/Hispanic,...,Major,Minor,Medical,Private Health Insurance,Self-Pay,NaN,NaN,Y,"29,998.00","5,083.57"

# Data Cleaning

In [20]:
df['Is_Neonate'] = df['Birth Weight'].notna().astype(int)
df['Birth Weight'] = df['Birth Weight'].fillna(0)

In [21]:
df.drop(columns=['Birth Weight'], inplace=True)

In [22]:
df['CCSR Procedure Code'] = df['CCSR Procedure Code'].replace('None', 'No Code').fillna('No Code')
df['CCSR Procedure Description'] = df['CCSR Procedure Description'].replace('None', 'No Procedure').fillna('No Procedure')

In [23]:
df['Zip Code - 3 digits'] = df['Zip Code - 3 digits'].fillna('Unknown')

In [24]:
facility_cols = ['Hospital Service Area', 'Hospital County', 'Operating Certificate Number', 'Permanent Facility Id']
df.dropna(subset=facility_cols, inplace=True)

In [25]:
df.dropna(subset=['APR Risk of Mortality', 'APR Severity of Illness Description'], inplace=True)

In [26]:
null_percentages = (df.isna().mean() * 100).round(2)
null_percentages[null_percentages > 0].sort_values(ascending=False)

Payment Typology 3    86.47
Payment Typology 2    52.82
dtype: float64

In [ ]:
missing_df = pd.DataFrame({
    'Missing_Count': df.isna().sum(),
    'Missing_Percentage_%': (df.isna().mean() * 100).round(2)
})

missing_df[missing_df['Missing_Count'] > 0].sort_values(by='Missing_Percentage_%', ascending=False)

                    Missing_Count  Missing_Percentage_%
Payment Typology 3        3646290                 86.47
Payment Typology 2        2227164                 52.82

In [28]:
df['Has_Secondary_Insurance'] = df['Payment Typology 2'].notna().astype('int8')

df = df.drop(columns=['Payment Typology 2', 'Payment Typology 3'])

In [29]:
missing_df = pd.DataFrame({
    'Missing_Count': df.isna().sum(),
    'Missing_Percentage_%': (df.isna().mean() * 100).round(10)
})

missing_df[missing_df['Missing_Count'] > 0].sort_values(by='Missing_Percentage_%', ascending=False)

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage_%]
Index: []

In [30]:
df.isna().sum().sum()

0

In [31]:
df.duplicated().sum().sum()

31915

In [32]:
df.drop_duplicates(inplace=True)

In [33]:
df.duplicated().sum().sum()

0

In [ ]:
df.to_parquet('cleaned_hospital_data_final.parquet', index=False)
print("Saved successfully! Size on disk")

Saved successfully! Size on disk