In [41]:
import pandas as pd

# Read Data

In [42]:
df1=pd.read_csv(r"Data before cleaning/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2022.csv")
df2=pd.read_csv(r"Data before cleaning/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2023.csv")

C:\Users\Hamza\AppData\Local\Temp\ipykernel_11500\3334157429.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv(r"Data before cleaning/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2022.csv")
C:\Users\Hamza\AppData\Local\Temp\ipykernel_11500\3334157429.py:2: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv(r"Data before cleaning/Hospital_Inpatient_Discharges__SPARCS_De-Identified___2023.csv")

In [43]:
df1.head()

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Manhattan,7002021.0,1454.0,Metropolitan Hospital Center,18 to 29,100,M,Other Race,Spanish/Hispanic,...,Moderate,Major,Medical,Self-Pay,NaN,NaN,NaN,Y,"21,943.33","19,793.21"
1,New York City,Queens,7003000.0,1626.0,Elmhurst Hospital Center,50 to 69,113,M,White,Unknown,...,Minor,Minor,Medical,Medicare,NaN,NaN,NaN,Y,"39,527.97","18,372.44"
2,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,M,Other Race,Unknown,...,Major,Major,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,"102,926.99","25,977.53"
3,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,50 to 69,109,M,White,Not Span/Hispanic,...,Major,Major,Medical,Medicare,NaN,NaN,NaN,Y,"85,344.09","18,830.76"
4,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,F,White,Not Span/Hispanic,...,Extreme,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"218,623.85","42,449.25"

In [44]:
df1.columns

Index(['Hospital Service Area', 'Hospital County',
       'Operating Certificate Number', 'Permanent Facility Id',
       'Facility Name', 'Age Group', 'Zip Code - 3 digits', 'Gender', 'Race',
       'Ethnicity', 'Length of Stay', 'Type of Admission',
       'Patient Disposition', 'Discharge Year', 'CCSR Diagnosis Code',
       'CCSR Diagnosis Description', 'CCSR Procedure Code',
       'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description',
       'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code',
       'APR Severity of Illness Description', 'APR Risk of Mortality',
       'APR Medical Surgical Description', 'Payment Typology 1',
       'Payment Typology 2', 'Payment Typology 3', 'Birth Weight',
       'Emergency Department Indicator', 'Total Charges', 'Total Costs'],
      dtype='object')

# Merge Data

In [45]:
df = pd.concat([df1, df2], ignore_index=True)

In [46]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4229187 entries, 0 to 4229186
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 6.5 GB

In [47]:
sum(df1.duplicated())

2923

In [48]:
sum(df2.duplicated())

2648

In [49]:
df.isna().sum()

Hospital Service Area                    10723
Hospital County                          10723
Operating Certificate Number             11294
Permanent Facility Id                    10723
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      83110
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                          0
CCSR Diagnosis Description                   0
CCSR Procedure Code                    1193839
CCSR Procedure Description             1193839
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description       1110
APR Risk of Mortality                     1110
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                     2235543
Payment Typology 3                     3657498
Birth Weight                           3816547
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [50]:
(df.isna().mean() * 100).round(2)

Hospital Service Area                   0.25
Hospital County                         0.25
Operating Certificate Number            0.27
Permanent Facility Id                   0.25
Facility Name                           0.00
Age Group                               0.00
Zip Code - 3 digits                     1.97
Gender                                  0.00
Race                                    0.00
Ethnicity                               0.00
Length of Stay                          0.00
Type of Admission                       0.00
Patient Disposition                     0.00
Discharge Year                          0.00
CCSR Diagnosis Code                     0.00
CCSR Diagnosis Description              0.00
CCSR Procedure Code                    28.23
CCSR Procedure Description             28.23
APR DRG Code                            0.00
APR DRG Description                     0.00
APR MDC Code                            0.00
APR MDC Description                     0.00
APR Severity of Illness Code            0.00
APR Severity of Illness Description     0.03
APR Risk of Mortality                   0.03
APR Medical Surgical Description        0.00
Payment Typology 1                      0.00
Payment Typology 2                     52.86
Payment Typology 3                     86.48
Birth Weight                           90.24
Emergency Department Indicator          0.00
Total Charges                           0.00
Total Costs                             0.00
dtype: float64

In [51]:
df

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Manhattan,7002021.0,1454.0,Metropolitan Hospital Center,18 to 29,100,M,Other Race,Spanish/Hispanic,...,Moderate,Major,Medical,Self-Pay,NaN,NaN,NaN,Y,"21,943.33","19,793.21"
1,New York City,Queens,7003000.0,1626.0,Elmhurst Hospital Center,50 to 69,113,M,White,Unknown,...,Minor,Minor,Medical,Medicare,NaN,NaN,NaN,Y,"39,527.97","18,372.44"
2,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,M,Other Race,Unknown,...,Major,Major,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,"102,926.99","25,977.53"
3,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,50 to 69,109,M,White,Not Span/Hispanic,...,Major,Major,Medical,Medicare,NaN,NaN,NaN,Y,"85,344.09","18,830.76"
4,Hudson Valley,Rockland,4324000.0,776.0,Montefiore Nyack,70 or Older,109,F,White,Not Span/Hispanic,...,Extreme,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"218,623.85","42,449.25"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4229182,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,115,M,Other Race,Not Span/Hispanic,...,Minor,Minor,Medical,Private Health Insurance,Self-Pay,NaN,NaN,Y,"27,074.71","4,718.63"
4229183,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,114,F,Other Race,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,Self-Pay,NaN,01900,N,"216,053.15","27,000.66"
4229184,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,109,F,White,Not Span/Hispanic,...,Minor,Minor,Medical,Medicaid,Medicaid,Self-Pay,NaN,Y,"24,867.76","4,291.06"
4229185,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,117,M,White,Spanish/Hispanic,...,Minor,Minor,Medical,Blue Cross/Blue Shield,Blue Cross/Blue Shield,Self-Pay,NaN,N,"46,873.00","6,210.75"
4229186,New York City,Queens,7003004.0,3376.0,Cohen Children's Medical Center,0 to 17,103,F,White,Not Span/Hispanic,...,Major,Minor,Medical,Private Health Insurance,Self-Pay,NaN,NaN,Y,"29,998.00","5,083.57"

In [52]:
df["CCSR Diagnosis Description"].unique()

array(['Bipolar and related disorders', 'Acute myocardial infarction',
       'Acute hemorrhagic cerebrovascular disease', 'Influenza',
       'Septicemia', 'COVID-19', 'Cardiac dysrhythmias', 'Heart failure',
       'Previous C-section', 'Acute and unspecified renal failure',
       'Chronic kidney disease', 'Alcohol-related disorders',
       'Urinary tract infections',
       'Skin and subcutaneous tissue infections', 'Prolonged pregnancy',
       'Maternal intrauterine infection', 'Intestinal infection',
       'Schizophrenia spectrum and other psychotic disorders',
       'Opioid-related disorders', 'Acute bronchitis',
       'Depressive disorders', 'Burn and corrosion, initial encounter',
       'Asthma', 'Fluid and electrolyte disorders', 'Syncope',
       'Acute pulmonary embolism', 'Skin/Subcutaneous signs and symptoms',
       'Osteoporosis', 'Intestinal obstruction and ileus',
       'Conduction disorders',
       'Other specified complications in pregnancy', 'Obesity',
       'Transient cerebral ischemia',
       'Diabetes mellitus with complication', 'Epilepsy; convulsions',
       'Personality disorders', 'Blindness and vision defects',
       'Respiratory cancers', 'Abdominal hernia',
       'Headache; including migraine',
       'Pneumonia (except that caused by tuberculosis)',
       'Nonspecific chest pain', 'Nervous system signs and symptoms',
       'Gastrointestinal hemorrhage', 'Cerebral infarction',
       'Pressure ulcer of skin', 'Pituitary disorders',
       'Early or threatened labor', 'Allergic reactions', 'Hypotension',
       'Viral infection', 'Anxiety and fear-related disorders',
       'Other specified and unspecified mood disorders',
       'Secondary malignancies', 'Neurodevelopmental disorders',
       'Trauma- and stressor-related disorders',
       'Diverticulosis and diverticulitis', 'Neurocognitive disorders',
       'Nervous system cancers - brain',
       'Retinal and vitreous conditions',
       'Respiratory failure; insufficiency; arrest', 'Multiple gestation',
       'Thyroid disorders',
       'Suicidal ideation/attempt/intentional self-harm', 'Dysphagia',
       'Poisoning by drugs, initial encounter',
       'Disruptive, impulse-control and conduct disorders', 'Hepatitis',
       'Coma; stupor; and brain damage', 'Meningitis',
       'Drug induced or toxic related condition',
       'Complications specified during childbirth',
       'Other nervous system disorders (often hereditary or degenerative)',
       'Malposition, disproportion or other labor complications',
       'Hypertension and hypertensive-related conditions complicating pregnancy; childbirth; and the puerperium',
       'Hypertension with complications and secondary hypertension',
       'Esophageal disorders', 'Gastritis and duodenitis',
       'Pancreatic disorders (excluding diabetes)',
       'Ectopic pregnancy and complications of ectopic pregnancy',
       'Noninfectious gastroenteritis', 'Liveborn',
       'Spondylopathies/spondyloarthropathy (including infective)',
       'Other specified and unspecified liver disease',
       'Complication of other surgical or medical care, injury, initial encounter',
       'Maternal care related to fetal conditions',
       'Fracture of the spine and back, initial encounter',
       'Sickle cell trait/anemia', 'Respiratory signs and symptoms',
       'Other specified and unspecified gastrointestinal disorders',
       'Other specified upper respiratory infections',
       'Varicose veins of lower extremity', 'Osteomyelitis',
       'Traumatic brain injury (TBI); concussion, initial encounter',
       'Other specified and unspecified skin disorders',
       'Other specified injury',
       'Postprocedural or postoperative digestive system complication',
       'Encounter for antineoplastic therapies',
       'Postthrombotic syndrome and venous insufficiency/hypertension',
       'Postprocedural or postoperative respiratory system complication',
       'Circulatory signs and symptoms',
       'Uncomplicated pregnancy, delivery or puerperium',
       'Other specified and unspecified nutritional and metabolic disorders',
       'Myopathies',
       'Diabetes or abnormal glucose tolerance complicating pregnancy; childbirth; or the puerperium',
       'Complication of genitourinary device, implant or graft, initial encounter',
       'Fracture of head and neck, initial encounter',
       'Other specified and unspecified diseases of kidney and ureters',
       'Muscle disorders', 'Malignant neuroendocrine tumors',
       'Head and neck cancers - nasopharyngeal', 'Non-Hodgkin lymphoma',
       'Fracture of torso, initial encounter',
       'Fracture of the upper limb, initial encounter',
       'Fracture of the lower limb (except hip), initial encounter',
       'Appendicitis and other appendiceal conditions',
       'Abdominal pain and other digestive/abdomen signs and symptoms',
       'Biliary tract disease',
       'Male reproductive system cancers - prostate',
       'Chronic rheumatic heart disease',
       'Open wounds to limbs, initial encounter',
       'Diseases of mouth; excluding dental',
       'OB-related trauma to perineum and vulva',
       'Maternal care related to disorders of the placenta and placental implantation',
       'Fracture of the neck of the femur (hip), initial encounter',
       'Peritonitis and intra-abdominal abscess',
       'Acute phlebitis; thrombophlebitis and thromboembolism',
       'Diseases of middle ear and mastoid (except otitis media)',
       'Pathological fracture, initial encounter',
       'Complication of internal orthopedic device or implant, initial encounter',
       'Sequela of cerebral infarction and other cerebrovascular disease',
       'Other specified substance-related disorders',
       'Aspiration pneumonitis', 'Osteoarthritis',
       'Gastrointestinal cancers - stomach',
       'Complication of cardiovascular device, implant or graft, initial encounter',
       'Nutritional anemia',
       'Other specified and unspecified lower respiratory disease',
       'Nonrheumatic and unspecified valve disorders',
       'Non-pressure ulcer of skin', 'Encephalitis',
       'Peripheral and visceral vascular disease',
       'Musculoskeletal congenital conditions',
       'Chronic obstructive pulmonary disease and bronchiectasis',
       'Nervous system congenital anomalies',
       'Breast cancer - all other types',
       'Postprocedural or postoperative circulatory system complication',
       'Polyhydramnios and other problems of amniotic cavity',
       'Complication of transplanted organs or tissue, initial encounter',
       'Pulmonary heart disease', 'Fever', 'Bacterial infections',
       'Endocarditis and endocardial disease',
       'Head and neck cancers - all other types',
       'Coronary atherosclerosis and other heart disease',
       'Female reproductive system cancers - endometrium',
       'Diseases of inner ear and related conditions', 'Cystic fibrosis',
       'Other general signs and symptoms',
       'Tendon and synovial disorders', 'Hepatic failure',
       'Gastroduodenal ulcer', 'Benign ovarian cyst',
       'Acquired deformities (excluding foot)',
       'Abnormal findings without diagnosis', 'Other aftercare encounter',
       'Cardiac and circulatory congenital anomalies',
       'Gastrointestinal cancers - liver',
       'Other specified female genital disorders',
       'Disorders of teeth and gingiva', 'Acute posthemorrhagic anemia',
       'Systemic lupus erythematosus and connective tissue disorders',
       'Gout', 'Noninfectious hepatitis',
       'Cardiac arrest and ventricular fibrillation',
       'Regional enteritis and ulcerative colitis', 'Pneumothorax',
       'Parkinson`s disease', 'Aplastic anemia', 'Sleep wake disorders',
       'Gastrointestinal cancers - colorectal',
       'Conditions due to neoplasm or the treatment of neoplasm',
       'Occlusion or stenosis of precerebral or cerebral arteries without infarction',
       'Maltreatment/abuse', 'Lung disease due to external agents',
       'Myelodysplastic syndrome (MDS)', 'Vesicoureteral reflux',
       'Malaise and fatigue', 'Paralysis (other than cerebral palsy)',
       'Head and neck cancers - lip and oral cavity', 'Polyneuropathies',
       'Multiple myeloma', 'Endocrine system cancers - pancreas',
       'Aortic; peripheral; and visceral artery aneurysms',
       'HIV infection', 'Disorders of jaw',
       'Other nervous system disorders (neither hereditary nor degenerative)',
       'Traumatic arthropathy',
       'Maternal care for abnormality of pelvic organs',
       'Coagulation and hemorrhagic disorders', 'Benign neoplasms',
       'Anal and rectal conditions',
       'Pericarditis and pericardial disease',
       'Nerve and nerve root disorders',
       'Spontaneous abortion and complications of spontaneous abortion',
       'Complications specified during the puerperium',
       'Diseases of white blood cells',
       'Leukemia - acute myeloid leukemia (AML)',
       'Pleurisy, pleural effusion and pulmonary collapse',
       'Nausea and vomiting', 'Stress fracture, initial encounter',
       'Postprocedural or postoperative skin complication',
       'Other specified and unspecified diseases of bladder and urethra',
       'Symptoms of mental and substance use conditions',
       'Stimulant-related disorders', 'Acute and chronic tonsillitis',
       'Other specified bone disease and musculoskeletal deformities',
       'Open wounds of head and neck, initial encounter',
       'General sensation/perception signs and symptoms',
       'Internal organ injury, initial encounter',
       'Nervous system cancers - all other types',
       'Scoliosis and other postural dorsopathic deformities',
       'Other and ill-defined cerebrovascular disease',
       'Leukemia - all other types',
       'Superficial injury; contusion, initial encounter',
       'Encounter for observation and examination for conditions ruled out (excludes infectious disease, neoplasm, mental disorders)',
       'Low back pain', 'Inflammatory conditions of male genital organs',
       'Musculoskeletal pain, not low back pain', 'Hemorrhoids',
       'Cerebral palsy', 'Nephritis; nephrosis; renal sclerosis',
       'Calculus of urinary tract', 'Other specified status',
       'CNS abscess',
       'Traumatic brain injury (TBI); concussion, subsequent encounter',
       'Other specified and unspecified endocrine disorders',
       'Hyperplasia of prostate',
       'Hemolytic jaundice and perinatal jaundice',
       'Other specified diseases of veins and lymphatics',
       'Other specified and unspecified disorders of the ear',
       'Urinary system cancers - bladder',
       'Effect of foreign body entering opening, initial encounter',
       'Myocarditis and cardiomyopathy',
       'Other specified and unspecified upper respiratory disease',
       'Inflammatory diseases of female pelvic organs',
       'Obsessive-compulsive and related disorders',
       'Fracture of lower limb (except hip), subsequent encounter',
       'Urinary system cancers - kidney',
       'Other specified and unspecified congenital anomalies',
       'Fracture of torso, subsequent encounter',
       'Nonmalignant breast conditions',
       'Postprocedural or postoperative musculoskeletal system complication',
       'Other specified and unspecified circulatory disease',
       'Acquired foot deformities', 'Fungal infections',
       'Infective arthritis',
       'Other specified inflammatory condition of skin',
       'Molar pregnancy and other abnormal products of conception',
       'Other and ill-defined heart disease',
       'Postprocedural or postoperative nervous system complication',
       'Hemolytic anemia', 'Cannabis-related disorders',
       'Neuro-ophthalmology', 'Sprains and strains, initial encounter',
       'Injury to nerves, muscles and tendons, initial encounter',
       'Neoplasms of unspecified nature or uncertain behavior',
       'Breast cancer - ductal carcinoma in situ (DCIS)',
       'Other specified and unspecified hematologic conditions',
       'Other specified eye disorders',
       'Gastrointestinal cancers - bile duct',
       'Oculofacial plastics and orbital conditions',
       'Burns and corrosion, subsequent encounter',
       'Other specified and unspecified disorders of stomach and duodenum',
       'Female reproductive system cancers - ovary',
       'Arterial dissections', 'Other specified male genital disorders',
       'Postprocedural or postoperative genitourinary system complication',
       'Effect of other external causes, initial encounter',
       'Hemorrhage after first trimester',
       'Head and neck cancers - laryngeal', 'Foodborne intoxications',
       'Fracture of the neck of the femur (hip), subsequent encounter',
       'Toxic effects, initial encounter', 'Hodgkin lymphoma',
       'Mesothelioma',
       'Other specified and unspecified perinatal conditions',
       'Other specified connective tissue disease',
       'Open wounds of trunk, initial encounter', 'Multiple sclerosis',
       'Shock', 'Nervous system pain and pain syndromes',
       'Perinatal infections', 'Injury, sequela',
       'Female reproductive system cancers - uterus',
       'Early, first or unspecified trimester hemorrhage',
       'Other specified joint disorders', 'Gangrene',
       'Gastrointestinal cancers - esophagus',
       'Open wounds of trunk, subsequent encounter',
       'Rheumatoid arthritis and related disease',
       'Essential hypertension', 'Somatic disorders',
       'Menstrual disorders', 'Feeding and eating disorders',
       'Crystal arthropathies (excluding gout)',
       'Other unspecified injury',
       'Short gestation; low birth weight; and fetal growth retardation',
       'Gastrointestinal cancers - small intestine',
       'Mental and substance use disorders in remission',
       'Induced abortion and complications of termination of pregnancy',
       'Head and neck cancers - eye', 'Digestive congenital anomalies',
       'Respiratory perinatal condition', 'Sarcoma',
       'Cancer of other sites', 'Sinusitis', 'Nutritional deficiencies',
       'Respiratory congenital malformations', 'Bone cancer',
       'Endometriosis', 'Neonatal cerebral disorders',
       'Neonatal digestive and feeding disorders',
       'Sexually transmitted infections (excluding HIV and hepatitis)',
       'Aseptic necrosis and osteonecrosis', 'Sedative-related disorders',
       'Genitourinary congenital anomalies',
       'Sequela of hemorrhagic cerebrovascular disease',
       'Hemorrhagic and hematologic disorders of newborn',
       'Injury to blood vessels, initial encounter',
       'Female reproductive system cancers - vagina',
       'Gastrointestinal and biliary perforation', 'Hematuria',
       'Female reproductive system cancers - vulva', 'Otitis media',
       'Endocrine system cancers - thyroid',
       'Gastrointestinal cancers - anus',
       'Miscellaneous mental and behavioral disorders/conditions',
       'Head and neck cancers - tonsils',
       'Head and neck cancers - hypopharyngeal',
       'Skin cancers - all other types', 'Skin cancers - melanoma',
       'Immunity disorders',
       'Encounter for prophylactic or other procedures',
       'Complication of internal orthopedic device or implant, subsequent encounter',
       'Head and neck cancers - salivary gland',
       'Skin cancers - squamous cell carcinoma',
       'Female reproductive system cancers - fallopian tube',
       'Complications of acute myocardial infarction',
       'Immune-mediated/reactive arthropathies',
       'Aortic and peripheral arterial embolism or thrombosis',
       'Tuberculosis', 'Malnutrition',
       'Sprains and strains, subsequent encounter',
       'Genitourinary signs and symptoms',
       'Gastrointestinal cancers - all other types',
       'Gastrointestinal cancers - gallbladder', 'Urinary incontinence',
       'Birth trauma', 'Malignant neoplasm, unspecified',
       'Cleft lip or palate', 'Cornea and external disease',
       'Spinal cord injury (SCI), initial encounter',
       'Leukemia - acute lymphoblastic leukemia (ALL)',
       'Dislocations, initial encounter', 'Disorders of lipid metabolism',
       'Biomechanical lesions',
       'Fracture of the upper limb, subsequent encounter',
       'Hallucinogen-related disorders',
       'Crushing injury, initial encounter',
       'Female reproductive system cancers - cervix',
       'Prolapse of female genital organs',
       'Dislocations, subsequent encounter',
       'Urinary system cancers - all other types',
       'Endocrine system cancers - adrenocortical',
       'Implant, device or graft related encounter',
       'Leukemia - chronic myeloid leukemia (CML)',
       'Mediastinal disorders', 'Menopausal disorders',
       'Exposure, encounters, screening or contact with infectious disease',
       'Fracture of the spine and back, subsequent encounter',
       'Acquired absence of limb or organ',
       'Male reproductive system cancers - testis',
       'Uveitis and ocular inflammation',
       'Endocrine system cancers - thymus',
       'Parasitic, other specified and unspecified infections',
       'Male reproductive system cancers - penis',
       'Toxic effects, subsequent encounter', 'Cardiac cancers',
       'Stress fracture, subsequent encounter',
       'Complication of cardiovascular device, implant or graft, subsequent encounter',
       'Pathological fracture, subsequent encounter',
       'Complication of genitourinary device, implant or graft, subsequent encounter',
       'Complication of other surgical or medical care, injury, subsequent encounter',
       'Open wounds of head and neck, subsequent encounter', 'Glaucoma',
       'Diabetes mellitus without complication',
       'Amputation of a limb, subsequent encounter',
       'Endocrine system cancers - all other types',
       'Neoplasm-related encounters', 'Leukemia - hairy cell',
       'Endocrine system cancers - parathyroid',
       'Urinary system cancers - ureter and renal pelvis',
       'Female reproductive system cancers - all other types',
       'Amputation of a limb, initial encounter',
       'Atypical fracture, initial encounter',
       'Spinal cord injury (SCI), subsequent encounter',
       'Contact dermatitis', 'Atypical fracture, subsequent encounter',
       'Respiratory distress syndrome',
       'Congenital malformations of eye, ear, face, neck',
       'Gastrointestinal cancers - peritoneum',
       'Leukemia - chronic lymphocytic leukemia (CLL)',
       'Musculoskeletal abscess', 'Neonatal abstinence syndrome',
       'Other specified CNS infection and poliomyelitis',
       'Postprocedural or postoperative endocrine or metabolic complication',
       'Obstetric history affecting care in pregnancy',
       'Head and neck cancers - throat',
       'Chronic phlebitis; thrombophlebitis and thromboembolism',
       'Complications following ectopic and/or molar pregnancy',
       'Erectile dysfunction', 'Cataract and other lens disorders',
       'Newborn affected by maternal conditions or complications of labor/delivery',
       'Pathological, stress and atypical fractures, sequela',
       'Head and neck cancers - pharyngeal',
       'Neonatal acidemia and hypoxia',
       'Internal organ injury, subsequent encounter',
       'Postprocedural or postoperative complications of the spleen',
       'Amputation of other body parts, initial encounter',
       'Other unspecified injuries, subsequent encounter',
       'Male infertility', 'Juvenile arthritis',
       'Medical examination/evaluation',
       'Male reproductive system cancers - all other types',
       'Proteinuria',
       'Adverse effects of drugs and medicaments, initial encounter',
       'Other specified injury, subsequent encounter',
       'Fracture of head and neck, subsequent encounter',

In [53]:
df['Age Group'].unique()

array(['18 to 29', '50 to 69', '70 or Older', '30 to 49', '0 to 17'],
      dtype=object)

In [54]:
df['Gender'].unique()

array(['M', 'F', 'U'], dtype=object)

In [55]:
df["Ethnicity"].unique()

array(['Spanish/Hispanic', 'Unknown', 'Not Span/Hispanic', 'Multi-ethnic'],
      dtype=object)

In [56]:
df['Ethnicity'].value_counts(dropna=False)

Ethnicity
Not Span/Hispanic    3033186
Spanish/Hispanic      667509
Unknown               518703
Multi-ethnic            9789
Name: count, dtype: int64

In [57]:
df['Type of Admission'].unique()

array(['Emergency', 'Elective', 'Urgent', 'Not Available', 'Newborn',
       'Trauma'], dtype=object)

In [58]:
df['Patient Disposition'].unique()

array(['Home or Self Care', 'Left Against Medical Advice', 'Expired',
       'Home w/ Home Health Services', 'Skilled Nursing Home',
       'Short-term Hospital', 'Hospice - Home',
       'Hospice - Medical Facility',
       'Psychiatric Hospital or Unit of Hosp',
       'Inpatient Rehabilitation Facility',
       'Medicaid Cert Nursing Facility',
       'Facility w/ Custodial/Supportive Care',
       'Medicare Cert Long Term Care Hospital',
       "Cancer Center or Children's Hospital", 'Another Type Not Listed',
       'Court/Law Enforcement', 'Federal Health Care Facility',
       'Critical Access Hospital',
       'Hosp Basd Medicare Approved Swing Bed'], dtype=object)

In [59]:
df['CCSR Diagnosis Code'].unique()

array(['MBD003', 'CIR009', 'CIR021', 'RSP003', 'INF002', 'INF012',
       'CIR017', 'CIR019', 'PRG016', 'GEN002', 'GEN003', 'MBD017',
       'GEN004', 'SKN001', 'PRG022', 'PRG021', 'DIG001', 'MBD001',
       'MBD018', 'RSP005', 'MBD002', 'INJ019', 'RSP009', 'END011',
       'SYM001', 'CIR013', 'SYM014', 'MUS013', 'DIG012', 'CIR016',
       'PRG028', 'END009', 'NVS012', 'END003', 'NVS009', 'MBD009',
       'EYE010', 'NEO022', 'DIG010', 'NVS010', 'RSP002', 'CIR012',
       'SYM010', 'DIG021', 'CIR020', 'SKN003', 'END013', 'PRG011',
       'INJ031', 'CIR031', 'INF008', 'MBD005', 'MBD004', 'NEO070',
       'MBD014', 'MBD007', 'DIG013', 'NVS011', 'NEO048', 'EYE005',
       'RSP012', 'PRG012', 'END001', 'MBD012', 'SYM005', 'INJ022',
       'MBD008', 'INF007', 'NVS013', 'NVS001', 'INJ030', 'PRG023',
       'NVS006', 'PRG024', 'PRG020', 'CIR008', 'DIG004', 'DIG007',
       'DIG020', 'PRG005', 'DIG022', 'PNL001', 'MUS011', 'DIG019',
       'INJ037', 'PRG013', 'INJ002', 'BLD005', 'SYM013', 'DIG025',
       'RSP006', 'CIR035', 'MUS002', 'INJ008', 'SKN007', 'INJ026',
       'DIG024', 'FAC006', 'CIR036', 'RSP017', 'SYM012', 'PRG029',
       'END016', 'NVS018', 'PRG019', 'INJ034', 'INJ001', 'GEN006',
       'MUS026', 'NEO066', 'NEO005', 'NEO058', 'INJ003', 'INJ004',
       'INJ005', 'DIG009', 'SYM006', 'DIG017', 'NEO039', 'CIR001',
       'INJ012', 'DIG003', 'PRG026', 'PRG018', 'INJ006', 'DIG016',
       'CIR033', 'EAR002', 'MUS014', 'INJ035', 'CIR025', 'MBD025',
       'RSP010', 'MUS006', 'NEO013', 'INJ033', 'BLD001', 'RSP016',
       'CIR003', 'SKN004', 'NVS002', 'CIR026', 'MAL008', 'RSP008',
       'MAL004', 'NEO030', 'CIR038', 'PRG014', 'INJ036', 'CIR014',
       'SYM002', 'INF003', 'CIR004', 'NEO010', 'CIR011', 'NEO035',
       'EAR003', 'END012', 'SYM016', 'MUS009', 'DIG018', 'DIG005',
       'GEN022', 'MUS023', 'SYM017', 'FAC010', 'MAL001', 'NEO017',
       'GEN025', 'DIG002', 'BLD004', 'MUS024', 'MUS033', 'DIG023',
       'CIR018', 'DIG011', 'RSP014', 'NVS004', 'BLD003', 'NVS016',
       'NEO015', 'NEO074', 'CIR023', 'INJ032', 'RSP013', 'NEO068',
       'GEN011', 'SYM007', 'NVS008', 'NEO002', 'NVS015', 'NEO065',
       'NEO051', 'CIR029', 'INF006', 'MUS029', 'NVS020', 'MUS031',
       'PRG017', 'BLD006', 'NEO073', 'DIG015', 'CIR006', 'NVS017',
       'PRG003', 'PRG027', 'BLD007', 'NEO060', 'RSP011', 'SYM004',
       'MUS016', 'SKN006', 'GEN007', 'SYM008', 'MBD021', 'RSP004',
       'MUS028', 'INJ011', 'SYM015', 'INJ010', 'NEO049', 'MUS022',
       'CIR024', 'NEO064', 'INJ017', 'FAC003', 'MUS038', 'GEN013',
       'MUS010', 'DIG014', 'NVS007', 'GEN001', 'GEN005', 'FAC025',
       'NVS014', 'INJ045', 'END015', 'GEN012', 'PNL007', 'CIR039',
       'EAR006', 'NEO043', 'INJ020', 'CIR005', 'RSP007', 'GEN018',
       'MBD006', 'INJ042', 'NEO045', 'MAL010', 'INJ040', 'GEN017',
       'MUS037', 'CIR032', 'MUS021', 'INF004', 'MUS001', 'SKN002',
       'PRG006', 'CIR015', 'NVS021', 'BLD002', 'MBD019', 'EYE006',
       'INJ024', 'INJ025', 'NEO072', 'NEO029', 'BLD010', 'EYE012',
       'NEO018', 'EYE008', 'INJ056', 'DIG008', 'NEO033', 'CIR027',
       'GEN016', 'GEN026', 'INJ021', 'PRG010', 'NEO008', 'INF005',
       'INJ043', 'INJ023', 'NEO057', 'NEO067', 'PNL013', 'MUS025',
       'INJ013', 'NVS005', 'SYM003', 'NVS019', 'PNL009', 'INJ073',
       'NEO031', 'PRG009', 'MUS007', 'CIR028', 'NEO012', 'INJ050',
       'MUS003', 'CIR007', 'MBD011', 'GEN021', 'MBD010', 'MUS034',
       'INJ027', 'PNL002', 'NEO014', 'MBD026', 'PRG004', 'NEO001',
       'MAL002', 'PNL006', 'NEO024', 'NEO069', 'RSP001', 'END007',
       'MAL007', 'NEO023', 'GEN019', 'PNL004', 'PNL012', 'INF010',
       'MUS030', 'MBD020', 'MAL003', 'CIR022', 'PNL011', 'INJ016',
       'NEO037', 'DIG006', 'GEN009', 'NEO036', 'EAR001', 'NEO050',
       'NEO016', 'MBD013', 'NEO009', 'NEO006', 'NEO028', 'NEO025',
       'BLD008', 'FAC004', 'INJ071', 'NEO004', 'NEO027', 'NEO034',
       'CIR010', 'MUS008', 'CIR030', 'INF001', 'END008', 'INJ061',
       'SYM011', 'NEO021', 'NEO019', 'GEN008', 'PNL008', 'NEO071',
       'MAL006', 'EYE001', 'INJ009', 'NEO059', 'INJ007', 'END010',
       'MUS012', 'INJ041', 'MBD022', 'INJ018', 'NEO032', 'GEN020',
       'INJ044', 'NEO047', 'NEO053', 'FAC009', 'NEO062', 'RSP015',
       'GEN023', 'FAC016', 'INJ039', 'FAC022', 'NEO040', 'EYE004',
       'NEO052', 'INF009', 'NEO041', 'INJ060', 'NEO011', 'MUS017',
       'INJ069', 'MUS015', 'INJ070', 'INJ072', 'INJ048', 'EYE003',
       'END002', 'INJ051', 'NEO056', 'FAC008', 'NEO063', 'NEO054',
       'NEO044', 'NEO038', 'INJ014', 'MUS018', 'INJ046', 'SKN005',
       'MUS019', 'PNL005', 'MAL005', 'NEO020', 'NEO061', 'MUS027',
       'PNL014', 'NVS003', 'END014', 'PRG015', 'NEO003', 'CIR034',
       'PRG007', 'GEN014', 'EYE002', 'PNL010', 'MUS020', 'NEO007',
       'PNL003', 'INJ047', 'BLD009', 'INJ015', 'INJ064', 'GEN015',
       'MUS004', 'FAC014', 'NEO042', 'GEN010', 'INJ028', 'INJ063',
       'INJ038', 'MUS032', 'INJ053', 'INJ049', 'FAC013', 'EAR005',
       'NEO046', 'MAL009', 'INJ058', 'NEO055', 'EAR004', 'FAC007',
       'NEO026', 'INJ059', 'MBD027', 'EYE007', 'CIR002', 'INJ057',
       'MBD023', 'PRG025', 'PRG001', 'EYE011', 'INJ076', 'INJ054',
       'INJ062', 'MUS036', 'INJ074', 'FAC020', 'NVS022', 'INJ068',
       'INJ055', 'INJ075', 'GEN024', 'EYE009', 'MUS035', 'FAC002',
       'INF011', 'MUS005', 'INJ067', 'MBD024', 'FAC012', 'XXX000',
       'NEO075', 'NEO078', 'INJ052', 'MBD034', 'SYM018', 'FAC001'],
      dtype=object)

In [60]:
df[['CCSR Diagnosis Code',
       'CCSR Diagnosis Description', 'CCSR Procedure Code',
       'CCSR Procedure Description', 'APR DRG Code', 'APR DRG Description',
       'APR MDC Code', 'APR MDC Description', 'APR Severity of Illness Code',
       'APR Severity of Illness Description', 'APR Risk of Mortality',
       'APR Medical Surgical Description']].head()

,CCSR Diagnosis Code,CCSR Diagnosis Description,CCSR Procedure Code,CCSR Procedure Description,APR DRG Code,APR DRG Description,APR MDC Code,APR MDC Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description
0,MBD003,Bipolar and related disorders,OTR004,ISOLATION PROCEDURES,753,BIPOLAR DISORDERS,19,MENTAL DISEASES AND DISORDERS,2,Moderate,Major,Medical
1,CIR009,Acute myocardial infarction,NaN,NaN,190,ACUTE MYOCARDIAL INFARCTION,5,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM,1,Minor,Minor,Medical
2,CIR021,Acute hemorrhagic cerebrovascular disease,NaN,NaN,44,INTRACRANIAL HEMORRHAGE,1,DISEASES AND DISORDERS OF THE NERVOUS SYSTEM,3,Major,Major,Medical
3,RSP003,Influenza,NaN,NaN,113,INFECTIONS OF UPPER RESPIRATORY TRACT,3,"DISEASES AND DISORDERS OF THE EAR, NOSE, MOUTH...",3,Major,Major,Medical
4,INF002,Septicemia,ESA003,MECHANICAL VENTILATION,720,SEPTICEMIA AND DISSEMINATED INFECTIONS,18,INFECTIOUS AND PARASITIC DISEASES (SYSTEMIC OR...,4,Extreme,Extreme,Medical

In [61]:
df['Discharge Year']

0          2022
1          2022
2          2022
3          2022
4          2022
           ...
4229182    2023
4229183    2023
4229184    2023
4229185    2023
4229186    2023
Name: Discharge Year, Length: 4229187, dtype: int64

In [62]:
df['Payment Typology 1'].unique()

array(['Self-Pay', 'Medicare', 'Medicaid', 'Private Health Insurance',
       'Blue Cross/Blue Shield', 'Federal/State/Local/VA',
       'Managed Care, Unspecified', 'Miscellaneous/Other',
       'Department of Corrections'], dtype=object)

In [63]:
df[['Payment Typology 2', 'Payment Typology 3']].value_counts()

Payment Typology 2         Payment Typology 3
Medicaid                   Self-Pay                     208192
Medicare                   Medicaid                     102116
                           Self-Pay                      41999
Private Health Insurance   Self-Pay                      29749
Blue Cross/Blue Shield     Self-Pay                      25849
                                                         ...
Medicare                   Department of Corrections         3
Managed Care, Unspecified  Miscellaneous/Other               2
Department of Corrections  Private Health Insurance          2
Self-Pay                   Federal/State/Local/VA            1
Private Health Insurance   Department of Corrections         1
Name: count, Length: 69, dtype: int64

In [64]:
df['CCSR Diagnosis Description'].value_counts()

CCSR Diagnosis Description
Liveborn                                                394980
Septicemia                                              289146
Heart failure                                           121121
Diabetes mellitus with complication                      83728
Alcohol-related disorders                                80443
                                                         ...
Osteomalacia                                                 1
Refractive error                                             1
Amputation of other body parts, subsequent encounter         1
Mental and substance use disorders; sequela                  1
Encounter for administrative purposes                        1
Name: count, Length: 486, dtype: int64

In [65]:
df[[    'CCSR Diagnosis Code',
        'CCSR Diagnosis Description',
        'APR MDC Description']
].drop_duplicates().head(30)

,CCSR Diagnosis Code,CCSR Diagnosis Description,APR MDC Description
0,MBD003,Bipolar and related disorders,MENTAL DISEASES AND DISORDERS
1,CIR009,Acute myocardial infarction,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM
2,CIR021,Acute hemorrhagic cerebrovascular disease,DISEASES AND DISORDERS OF THE NERVOUS SYSTEM
3,RSP003,Influenza,"DISEASES AND DISORDERS OF THE EAR, NOSE, MOUTH..."
4,INF002,Septicemia,INFECTIOUS AND PARASITIC DISEASES (SYSTEMIC OR...
5,INF012,COVID-19,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM
6,CIR017,Cardiac dysrhythmias,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM
7,CIR019,Heart failure,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM
8,PRG016,Previous C-section,"PREGNANCY, CHILDBIRTH AND THE PUERPERIUM"
9,GEN002,Acute and unspecified renal failure,DISEASES AND DISORDERS OF THE KIDNEY AND URINA...
10,GEN003,Chronic kidney disease,DISEASES AND DISORDERS OF THE KIDNEY AND URINA...
12,MBD017,Alcohol-related disorders,ALCOHOL/DRUG USE AND ALCOHOL/DRUG INDUCED ORGA...
14,GEN004,Urinary tract infections,DISEASES AND DISORDERS OF THE KIDNEY AND URINA...
16,SKN001,Skin and subcutaneous tissue infections,"DISEASES AND DISORDERS OF THE SKIN, SUBCUTANEO..."
18,INF012,COVID-19,HUMAN IMMUNODEFICIENCY VIRUS INFECTIONS
23,PRG022,Prolonged pregnancy,"PREGNANCY, CHILDBIRTH AND THE PUERPERIUM"
25,PRG021,Maternal intrauterine infection,"PREGNANCY, CHILDBIRTH AND THE PUERPERIUM"
26,DIG001,Intestinal infection,DISEASES AND DISORDERS OF THE DIGESTIVE SYSTEM
29,MBD001,Schizophrenia spectrum and other psychotic dis...,MENTAL DISEASES AND DISORDERS
33,MBD018,Opioid-related disorders,ALCOHOL/DRUG USE AND ALCOHOL/DRUG INDUCED ORGA...
35,RSP005,Acute bronchitis,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM
39,MBD002,Depressive disorders,MENTAL DISEASES AND DISORDERS
42,INJ019,"Burn and corrosion, initial encounter",BURNS
44,RSP009,Asthma,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM
45,END011,Fluid and electrolyte disorders,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES ..."
49,SYM001,Syncope,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM
53,GEN003,Chronic kidney disease,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM
55,CIR013,Acute pulmonary embolism,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM
56,SYM014,Skin/Subcutaneous signs and symptoms,DISEASES AND DISORDERS OF THE NERVOUS SYSTEM
59,MUS013,Osteoporosis,DISEASES AND DISORDERS OF THE MUSCULOSKELETAL ...

In [66]:
diagnosis_mapping = (
    df.groupby('CCSR Diagnosis Code')
      .agg(
          Diagnosis=('CCSR Diagnosis Description', 'nunique'),
          MDC_Groups=('APR MDC Description', 'nunique')
      )
      .sort_values('MDC_Groups', ascending=False)
)

display(diagnosis_mapping.head(20))

                     Diagnosis  MDC_Groups
CCSR Diagnosis Code
NEO073                       1          32
SYM017                       1          27
INJ030                       1          27
NEO072                       1          26
INF010                       1          25
END016                       1          24
INJ037                       1          24
SYM016                       1          21
NEO070                       1          21
BLD008                       1          19
INJ010                       1          19
INJ036                       1          19
PNL013                       1          18
END003                       1          17
INF001                       1          17
MAL010                       1          16
INJ020                       1          15
NEO024                       1          15
INJ013                       1          15
INJ026                       1          15

-------

# Data Cleaning

In [67]:
df['Birth Weight'] = pd.to_numeric(
    df['Birth Weight'].astype('string').str.strip(),
    errors='coerce'
)

print(df['Birth Weight'].dtype)

Float64

In [68]:
df['Is_Neonate'] = df['Birth Weight'].notna().astype(int)
df['Birth Weight'] = df['Birth Weight'].fillna(0)

In [69]:
df['CCSR Procedure Code'] = df['CCSR Procedure Code'].replace('None', 'No Code').fillna('No Code')
df['CCSR Procedure Description'] = df['CCSR Procedure Description'].replace('None', 'No Procedure').fillna('No Procedure')

In [70]:
df['Zip Code - 3 digits'] = df['Zip Code - 3 digits'].fillna('Unknown')

In [71]:
facility_cols = [
    'Hospital Service Area',
    'Hospital County',
    'Operating Certificate Number',
    'Permanent Facility Id'
]

missing_rows = df[facility_cols].isna().any(axis=1).sum()

print(f"Rows to be dropped: {missing_rows}")
print(f"Percentage: {missing_rows / len(df) * 100:.2f}%")

Rows to be dropped: 11294
Percentage: 0.27%

In [72]:
facility_cols = ['Hospital Service Area', 'Hospital County', 'Operating Certificate Number', 'Permanent Facility Id']
df.dropna(subset=facility_cols, inplace=True)

In [73]:
df.dropna(subset=['APR Risk of Mortality', 'APR Severity of Illness Description'], inplace=True)

In [74]:
null_percentages = (df.isna().mean() * 100).round(2)
null_percentages[null_percentages > 0].sort_values(ascending=False)

Payment Typology 3    86.47
Payment Typology 2    52.82
dtype: float64

In [75]:
missing_df = pd.DataFrame({
    'Missing_Count': df.isna().sum(),
    'Missing_Percentage_%': (df.isna().mean() * 100).round(2)
})

missing_df[missing_df['Missing_Count'] > 0].sort_values(by='Missing_Percentage_%', ascending=False)

                    Missing_Count  Missing_Percentage_%
Payment Typology 3        3646290                 86.47
Payment Typology 2        2227164                 52.82

In [76]:
df['Has_Secondary_Insurance'] = df['Payment Typology 2'].notna().astype('int8')

df = df.drop(columns=['Payment Typology 2', 'Payment Typology 3'])

In [77]:
df.isna().sum().sum()

0

In [78]:
df.duplicated().sum().sum()

8100

In [79]:
df.drop_duplicates(inplace=True)

In [80]:
df.duplicated().sum()

0

In [81]:
df.to_parquet('cleaned_hospital_data_final.parquet', index=False)

print("Parquet file saved successfully!")

Parquet file saved successfully!